[package]
name = "mbcc-pkg"
version = "0.1.0"
authors = ["unknown <unknown@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liboh = { git = "https://github.com/pitust/liboh" }
rlibc = "1.0.0"
postcard = { version = "0.5.1", features = ["alloc"] }
serde = { version = "1.0.117", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0.59", default-features = false, features = ["alloc"] }
serde_derive = "1.0.117"